minor refactor of setup

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -186,40 +186,34 @@ set -Eeuo pipefail
     exit 1
   }
 
+  cmd_check() {
+    for cmd in "$@"; do
+      has_cmd "$1" || die "$1 not installed. Quitting."
+    done
+  }
+
   pixi_install() {
     log "Installing pixi and essential packages..."
     if ! has_cmd pixi; then
       curl -fsSL https://pixi.sh/install.sh | sh
     fi
-    has_cmd pixi || die "pixi not installed or not in PATH. Quitting."
+    cmd_check pixi || die "pixi not installed or not in PATH. Quitting."
   }
 
   packages_install() {
-    has_cmd git || si git
-    has_cmd git || die "git not installed. Quitting."
+    has_cmd git || si git || true
+    cmd_check git
 
-    has_cmd trash || si trash-cli
+    has_cmd trash || si trash-cli || true
     has_cmd trash || pixi global install trash-cli
+    cmd_check trash
 
-    has_cmd stow || si stow
+    has_cmd stow || si stow || true
     has_cmd stow || pixi global install stow
-
+    has_cmd starship || pixi global install starship
     has_cmd gum || pixi global install go-gum
-
     pixi global install nushell
-    has_cmd nu || die "nu not installed. Quitting"
-  }
-
-  base_install() {
-    log "Installing required packages..."
-    update_packages
-
-    has_cmd curl || si curl
-    has_cmd curl || die "curl not installed. Quitting."
-
-    pixi_install
-
-    packages_install
+    cmd_check stow starship gum nushell
   }
 
   add_paths() {
@@ -251,8 +245,16 @@ set -Eeuo pipefail
       die "Only Fedora, Ubuntu Questing, Tumbleweed, Arch, Debian Trixie and PikaOS supported. Quitting."
     }
 
-    base_install
+    update_packages
+
+    log "Installing required packages..."
+    has_cmd curl || si curl || true
+    has_cmd curl || die "curl not installed. Quitting."
+
+    pixi_install
+    packages_install
     dotfiles_clone
+
     nu ~/.local/share/linux-config/nu/setup.nu
   }
 
