minor fixes

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -50,17 +50,17 @@ init_logs() {
 }
 
 log() {
-  printf "\033[1;34mℹ\033[0m %s\n" "$*"
+  printf "\033[1;34mℹ %s\033[0m\n" "$*"
   printf "INFO: %s\n" "$*" >>"${LOG_FILE}"
 }
 
 warn() {
-  printf "\033[1;33m⚠\033[0m %s\n" "$*"
+  printf "\033[1;33m⚠ %s\033[0m\n" "$*"
   printf "WARNING: %s\n" "$*" >>"${LOG_FILE}"
 }
 
 error() {
-  printf "\033[1;31m✖\033[0m %s\n" "$*" >&2
+  printf "\033[1;31m✖ %s\033[0m\n" "$*" >&2
   printf "ERROR: %s\n" "$*" >>"${LOG_FILE}"
 }
 
@@ -78,13 +78,14 @@ cmd_check() {
 }
 
 cmd_checks() {
-  local total="$#"
-  local i=0
+  local all_found=true
   for cmd in "$@"; do
-    has_cmd "$cmd" || warn "Command $cmd not found."
-    ((i++))
+    if ! has_cmd "$cmd"; then
+      warn "Command $cmd not found."
+      all_found=false
+    fi
   done
-  [[ ! $i -eq $total ]] && die "Some commands were not found."
+  $all_found || die "Some commands were not found."
 }
 
 system_update() {
@@ -176,7 +177,7 @@ pixi_packages_install() {
 
   log "Installing pixi packages..."
   pixi global install nushell go-gum trash-cli starship gh
-  cmd_checks nushell gum trash starship gh
+  cmd_checks nu gum trash starship gh
 }
 
 brew_install() {
@@ -255,7 +256,7 @@ fish_config() {
   has_cmd fish || si fish
   cmd_check fish
 
-  if ! link "${DOT_DIR}/fish/dot-config/config.fish" "${HOME}/.config/fish/config.fish"; then
+  if ! link "${DOT_DIR}/fish/dot-config/fish/config.fish" "${HOME}/.config/fish/config.fish"; then
     die "Failed to link: ${DOT_DIR}/fish/config.fish -> ${HOME}/.config/fish/config.fish"
   fi
 
